name: Build and Push voting-app to ECR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: agbor

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker and Docker Compose
        run: |
          # Update packages
          sudo apt-get update -y

          # Install Docker Engine
          sudo apt-get install -y ca-certificates curl gnupg lsb-release
          sudo mkdir -p /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/$(. /etc/os-release && echo "$ID")/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
          echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
            https://download.docker.com/linux/$(. /etc/os-release && echo "$ID") \
            $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

          sudo apt-get update -y
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin

          # Verify versions
          docker --version
          docker compose version
          sudo chmod 666 /var/run/docker.sock

      - name: Deploy voting-app stack
        run: |
          # Recommended to use the new syntax
          docker compose up -d
