name: Build and Push voting-app to ECR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: agbor

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker and Docker Compose
        run: |
          echo "🧱 Updating packages..."
          sudo apt-get update -y

          echo "🔧 Installing dependencies..."
          sudo apt-get install -y ca-certificates curl gnupg lsb-release
          sudo mkdir -p /etc/apt/keyrings

          echo "🔑 Adding Docker’s official GPG key..."
          curl -fsSL https://download.docker.com/linux/$(. /etc/os-release && echo "$ID")/gpg \
            | sudo gpg --batch --yes --dearmor -o /etc/apt/keyrings/docker.gpg

          echo "📦 Setting up Docker repository..."
          echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
            https://download.docker.com/linux/$(. /etc/os-release && echo "$ID") \
            $(lsb_release -cs) stable" \
            | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

          echo "🚀 Installing Docker Engine and Compose..."
          sudo apt-get update -y
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin

          echo "✅ Docker and Compose versions:"
          docker --version
          docker compose version

          echo "🔓 Fixing Docker socket permissions..."
          sudo chmod 666 /var/run/docker.sock

          echo "🐳 Checking running containers..."
          docker ps -a

      - name: Deploy voting-app stack
        run: |
          echo "🚀 Starting voting-app stack..."
          docker compose -p votingapp up -d

  dockerhub-login:
    name: Login to Docker Hub
    needs: build
    runs-on: agbor

    steps:
      - name: Install Docker CLI (if not available)
        run: |
          if ! command -v docker &> /dev/null; then
            echo "🐳 Installing Docker CLI..."
            sudo apt-get update -y
            sudo apt-get install -y docker-ce-cli
          fi

      - name: Login to Docker Hub
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          echo "🔐 Logging into Docker Hub..."
          echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
          echo "✅ Successfully logged into Docker Hub!"
